name: Weekday Markdown Generator

permissions:
  contents: write  # 允許 push 變更

# Update schedule comment
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  generate-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Markdown file
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          DATE=$(date +'%Y-%m-%d')

          mkdir -p "$YEAR/$MONTH"

          FILE="$YEAR/$MONTH/$DATE.md"

          echo "# $DATE" > "$FILE"
          echo "" >> "$FILE"
          echo "## 今日進度" >> "$FILE"
          echo "- " >> "$FILE"
          echo "" >> "$FILE"
          echo "## 明日待辦" >> "$FILE"
          echo "- " >> "$FILE"
          echo "" >> "$FILE"
          echo "## 備註(雜記)" >> "$FILE"
          echo "- " >> "$FILE"

      - name: Commit and push file
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          DATE=$(date +'%Y-%m-%d')

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add "$YEAR/$MONTH/$DATE.md"
          git commit -m "Add daily log for $DATE" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

